package edu.univ1.service;
import edu.univ1.api.*;
import edu.univ1.auth.*;
import edu.univ1.data.*;
import edu.univ1.domain.*;
import edu.univ1.util.*;
import edu.univ1.ui.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

public class NotificationService{
    private final NotificationDAO notificationDAO=new NotificationDAO();
    public List<Notification> getStudentNotifications(){
        return notificationDAO.getActiveByAudience("STUDENT",10);
    }
    public List<Notification> getRecentNotifications(int limit){
        return notificationDAO.getRecent(limit);
    }
    public long publishManualNotification(String title,String message,String createdBy,LocalDate expiresOn){
        Notification notification=new Notification();
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setAudience("STUDENT");
        notification.setCategory("MANUAL");
        notification.setAutoGenerated(false);
        notification.setCreatedBy(createdBy);
        if(expiresOn!=null){
            notification.setExpiresAt(expiresOn.atStartOfDay().plusDays(1));
        }
        return notificationDAO.insert(notification);
    }
    public long publishMaintenanceStatus(boolean enabled){
        String title=enabled ? "Maintenance Window" : "Maintenance Complete";
        String message=enabled
                ? "The system is currently under maintenance. Some operations are unavailable."
                : "Maintenance has concluded and services are restored.";
        Notification notification=new Notification();
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setAudience("STUDENT");
        notification.setCategory("MAINTENANCE");
        notification.setAutoGenerated(true);
        notification.setCreatedBy("system");
        notification.setExpiresAt(LocalDateTime.now().plusDays(1));
        return notificationDAO.insert(notification);
    }
    public long publishDeadlineUpdate(LocalDate registerDeadline, LocalDate dropDeadline){
        StringBuilder message=new StringBuilder();
        if(registerDeadline!=null){
            message.append("Registration deadline: ").append(registerDeadline).append(". ");
        }
        if(dropDeadline!=null){
            message.append("Drop deadline: ").append(dropDeadline).append(". ");
        }
        if(message.length()==0){
            return -1;
        }
        Notification notification=new Notification();
        notification.setTitle("Academic Deadlines Updated");
        notification.setMessage(message.toString().trim());
        notification.setAudience("STUDENT");
        notification.setCategory("DEADLINE");
        notification.setAutoGenerated(true);
        notification.setCreatedBy("system");
        notification.setExpiresAt(LocalDateTime.now().plusDays(7));
        return notificationDAO.insert(notification);
    }
    public boolean delete(long notificationId){
        return notificationDAO.delete(notificationId);
    }
}