package edu.univ1.domain;
import java.time.LocalDateTime;

public class Notification{
    private long notificationId;
    private String title;
    private String message;
    private String audience;
    private String category;
    private boolean autoGenerated;
    private String createdBy;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;
    public long getNotificationId(){
        return notificationId;
    }
    public void setNotificationId(long notificationId){
        this.notificationId=notificationId;
    }
    public String getTitle(){
        return title;
    }
    public void setTitle(String title){
        this.title=title;
    }
    public String getMessage(){
        return message;
    }
    public void setMessage(String message){
        this.message=message;
    }
    public String getAudience(){
        return audience;
    }
    public void setAudience(String audience){
        this.audience=audience;
    }
    public String getCategory(){
        return category;
    }
    public void setCategory(String category){
        this.category=category;
    }
    public boolean isAutoGenerated(){
        return autoGenerated;
    }
    public void setAutoGenerated(boolean autoGenerated){
        this.autoGenerated=autoGenerated;
    }
    public String getCreatedBy(){
        return createdBy;
    }
    public void setCreatedBy(String createdBy){
        this.createdBy=createdBy;
    }
    public LocalDateTime getCreatedAt(){
        return createdAt;
    }
    public void setCreatedAt(LocalDateTime createdAt){
        this.createdAt=createdAt;
    }
    public LocalDateTime getExpiresAt(){
        return expiresAt;
    }
    public void setExpiresAt(LocalDateTime expiresAt){
        this.expiresAt=expiresAt;
    }
}