package edu.univ1.data;
import edu.univ1.api.*;
import edu.univ1.auth.*;
import edu.univ1.domain.*;
import edu.univ1.service.*;
import edu.univ1.ui.*;
import edu.univ1.util.*;
import javax.sql.DataSource;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class NotificationDAO{
    private final DataSource dataSource;
    public NotificationDAO(){
        this.dataSource=ERPDataSource.getDataSource();
    }
    public long insert(Notification notification){
        String sql="INSERT INTO notifications(title, message, audience, category, auto_generated, created_by, expires_at) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?)";
        try(Connection conn=dataSource.getConnection();
            PreparedStatement stmt=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){
            stmt.setString(1,notification.getTitle());
            stmt.setString(2,notification.getMessage());
            stmt.setString(3,notification.getAudience());
            stmt.setString(4,notification.getCategory());
            stmt.setBoolean(5,notification.isAutoGenerated());
            stmt.setString(6,notification.getCreatedBy());
            if(notification.getExpiresAt()!=null){
                stmt.setTimestamp(7,Timestamp.valueOf(notification.getExpiresAt()));
            }else{
                stmt.setNull(7,Types.TIMESTAMP);
            }
            int rows=stmt.executeUpdate();
            if(rows>0){
                ResultSet keys=stmt.getGeneratedKeys();
                if(keys.next()){
                    return keys.getLong(1);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return -1;
    }
    public List<Notification>getActiveByAudience(String audience,int limit){
        List<Notification> list=new ArrayList<>();
        String sql="SELECT * FROM notifications "+
                "WHERE (audience = ? OR audience = 'ALL') "+
                "AND (expires_at IS NULL OR expires_at >= NOW()) "+
                "ORDER BY created_at DESC LIMIT ?";
        try(Connection conn=dataSource.getConnection();
            PreparedStatement stmt=conn.prepareStatement(sql)){
            stmt.setString(1,audience);
            stmt.setInt(2,limit);
            ResultSet rs=stmt.executeQuery();
            while(rs.next()){
                list.add(mapRow(rs));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return list;
    }
    public List<Notification>getRecent(int limit){
        List<Notification> list=new ArrayList<>();
        String sql="SELECT * FROM notifications ORDER BY created_at DESC LIMIT ?";
        try(Connection conn=dataSource.getConnection();
             PreparedStatement stmt=conn.prepareStatement(sql)){
            stmt.setInt(1,limit);
            ResultSet rs=stmt.executeQuery();
            while(rs.next()){
                list.add(mapRow(rs));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return list;
    }
    public boolean delete(long notificationId){
        String sql="DELETE FROM notifications WHERE notification_id=?";
        try(Connection conn=dataSource.getConnection();
            PreparedStatement stmt=conn.prepareStatement(sql)){
            stmt.setLong(1,notificationId);
            return stmt.executeUpdate()>0;
        }catch(Exception e){
            e.printStackTrace();
        }
        return false;
    }
    private Notification mapRow(ResultSet rs) throws SQLException{
        Notification n=new Notification();
        n.setNotificationId(rs.getLong("notification_id"));
        n.setTitle(rs.getString("title"));
        n.setMessage(rs.getString("message"));
        n.setAudience(rs.getString("audience"));
        n.setCategory(rs.getString("category"));
        n.setAutoGenerated(rs.getBoolean("auto_generated"));
        n.setCreatedBy(rs.getString("created_by"));
        Timestamp createdAt=rs.getTimestamp("created_at");
        Timestamp expiresAt=rs.getTimestamp("expires_at");
        if(createdAt!=null){
            n.setCreatedAt(createdAt.toLocalDateTime());
        }
        if(expiresAt!=null){
            n.setExpiresAt(expiresAt.toLocalDateTime());
        }
        return n;
    }
}